# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-17 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carte',
            name='date_delivrance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carte',
            name='date_mise_opposition',
            field=models.DateField(blank=True, null=True),
        ),
    ]
