# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-17 10:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_auto_20170517_0939'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='carte',
            unique_together=set([('statut', 'porteur')]),
        ),
    ]
