# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-07-04 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_auto_20170517_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Gestion des Services',
            },
        ),
        migrations.CreateModel(
            name='SouscriptionSvc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Service')),
                ('usager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Porteur')),
            ],
            options={
                'verbose_name_plural': 'Service souscrit',
            },
        ),
    ]
