# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-05 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_service_souscriptionsvc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bornes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('lieu', models.CharField(max_length=100)),
                ('etat', models.IntegerField(choices=[(1, 'Active'), (2, 'HS')], default=1)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Service')),
            ],
            options={
                'verbose_name_plural': 'Gestion des bornes',
            },
        ),
        migrations.AlterUniqueTogether(
            name='bornes',
            unique_together=set([('etat', 'service')]),
        ),
    ]
