# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-08-23 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_auto_20170805_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='bornes',
            name='adresse_ip',
            field=models.GenericIPAddressField(default='192.168.2.0', protocol='IPv4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='souscriptionsvc',
            name='date_debut',
            field=models.DateField(blank=True, null=True, verbose_name='Date de d\xe9but'),
        ),
    ]
