# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-08-23 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_auto_20170823_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='bornes',
            name='adresse_mac',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Adresse MAC'),
        ),
    ]
