# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-08-24 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_auto_20170824_1034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='porteur',
            options={'verbose_name_plural': 'Gestion des Adh\xe9rents'},
        ),
        migrations.RemoveField(
            model_name='carte',
            name='date_delivrance',
        ),
        migrations.RemoveField(
            model_name='carte',
            name='date_mise_opposition',
        ),
        migrations.AddField(
            model_name='carte',
            name='date_activation',
            field=models.DateField(blank=True, null=True, verbose_name='Date activation'),
        ),
        migrations.AddField(
            model_name='carte',
            name='date_inactivation',
            field=models.DateField(blank=True, null=True, verbose_name='Date inactivation'),
        ),
        migrations.AddField(
            model_name='souscriptionsvc',
            name='date_reglement',
            field=models.DateField(blank=True, null=True, verbose_name='Date de r\xe9glement'),
        ),
    ]
