# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-08-24 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_auto_20170824_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carte',
            name='date_inactivation',
        ),
        migrations.AddField(
            model_name='carte',
            name='date_desactivation',
            field=models.DateField(blank=True, null=True, verbose_name='Date de d\xe9sactivation'),
        ),
        migrations.AddField(
            model_name='carte',
            name='motif',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='carte',
            name='date_activation',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'activation"),
        ),
    ]
