# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-08-29 09:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_auto_20170824_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='souscriptionsvc',
            old_name='usager',
            new_name='porteur',
        ),
    ]
