# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-08-31 10:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0012_auto_20170829_1135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bornes',
            options={'ordering': ['nom'], 'verbose_name_plural': 'Gestion des Bornes'},
        ),
        migrations.AlterModelOptions(
            name='carte',
            options={'ordering': ['code', 'porteur'], 'verbose_name_plural': 'Gestion des Cartes'},
        ),
        migrations.AlterModelOptions(
            name='porteur',
            options={'ordering': ['nom', 'prenom'], 'verbose_name_plural': 'Gestion des Adh\xe9rents'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['nom'], 'verbose_name_plural': 'Gestion des Services'},
        ),
    ]
