# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-09-02 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0013_auto_20170831_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='porteur',
            name='mot_de_passe',
            field=models.CharField(default='bienvenue', max_length=30),
        ),
    ]
