# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-09-02 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0014_porteur_mot_de_passe'),
    ]

    operations = [
        migrations.AddField(
            model_name='porteur',
            name='adresse_mail',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='courriel'),
        ),
        migrations.AddField(
            model_name='porteur',
            name='identifiant',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Identifiant compte'),
        ),
        migrations.AlterField(
            model_name='porteur',
            name='mot_de_passe',
            field=models.CharField(blank=True, default='bienvenue', max_length=30, null=True),
        ),
    ]
