# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-09-12 11:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0015_auto_20170902_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bornes',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.Service'),
        ),
        migrations.AlterField(
            model_name='carte',
            name='porteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.Porteur'),
        ),
    ]
