# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-09-19 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0018_auto_20170912_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='porteur',
            name='statut',
            field=models.IntegerField(choices=[(1, 'Actif'), (2, 'Inactif')], default=1),
        ),
    ]
